### ISSUE TITLE
[BUG] Compilation failure when indexing 32-bit int wire arrays

### ISSUE THREAD

**Issue by glassnotes** [PennyLaneAI/catalyst#613]
#### Issue description

* *Expected behavior:* Integer arrays of wires can be created and indexed within a QNode using default JAX behaviour.

* *Actual behavior:* Trying to apply an operation to a wire from a list of 32-bit ints throws an error as `quantum.extract` expects a 64-bit signless integer.

* *Reproduces how often:* Always

* *System information:* (post the output of `import pennylane as qml; qml.about()`)

My install of Catalyst is from the branch ac3b90f9b69fefa0f24b15946ddfeacf6be36949.

```
Name: PennyLane
Version: 0.35.1
Summary: PennyLane is a cross-platform Python library for quantum computing, quantum machine learning, and quantum chemistry. Train a quantum computer the same way as a neural network.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /home/olivia/.conda/envs/shortalyst/lib/python3.11/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml, typing-extensions
Required-by: amazon-braket-pennylane-plugin, PennyLane-Catalyst, PennyLane_Lightning, PennyLane_Lightning_Kokkos

Platform info:           Linux-6.5.0-25-generic-x86_64-with-glibc2.35
Python version:          3.11.8
Numpy version:           1.26.4
Scipy version:           1.12.0
Installed devices:
- default.clifford (PennyLane-0.35.1)
- default.gaussian (PennyLane-0.35.1)
- default.mixed (PennyLane-0.35.1)
- default.qubit (PennyLane-0.35.1)
- default.qubit.autograd (PennyLane-0.35.1)
- default.qubit.jax (PennyLane-0.35.1)
- default.qubit.legacy (PennyLane-0.35.1)
- default.qubit.tf (PennyLane-0.35.1)
- default.qubit.torch (PennyLane-0.35.1)
- default.qutrit (PennyLane-0.35.1)
- null.qubit (PennyLane-0.35.1)
- lightning.kokkos (PennyLane_Lightning_Kokkos-0.35.1)
- nvidia.custatevec (PennyLane-Catalyst-0.6.0.dev0)
- nvidia.cutensornet (PennyLane-Catalyst-0.6.0.dev0)
- softwareq.qpp (PennyLane-Catalyst-0.6.0.dev0)
- braket.aws.ahs (amazon-braket-pennylane-plugin-1.24.6)
- braket.aws.qubit (amazon-braket-pennylane-plugin-1.24.6)
- braket.local.ahs (amazon-braket-pennylane-plugin-1.24.6)
- braket.local.qubit (amazon-braket-pennylane-plugin-1.24.6)
- lightning.qubit (PennyLane_Lightning-0.35.1)
```

#### Source code and tracebacks

Here is a minimal example:

```python

import pennylane as qml
import jax.numpy as jnp

@qml.qjit
def create_and_run_qnode():
    # int32 is the default type when creating an array; change to jnp.int64 to avoid error
    wires = jnp.arange(0, 4, dtype=jnp.int32) 
    dev = qml.device("lightning.qubit", wires=wires)

    @qml.qnode(dev)
    def circuit():
        qml.Hadamard(wires=wires[0])
        return qml.probs(wires=dev.wires)

    return circuit()

create_and_run_qnode()
```

The error message I receive is

```
Traceback (most recent call last):
  File "/home/olivia/Code/catalyst/frontend/catalyst/compiler.py", line 460, in run_from_ir
    compiler_output = run_compiler_driver(
                      ^^^^^^^^^^^^^^^^^^^^
RuntimeError: Compilation failed:
create_and_run_qnode:30:10: error: 'quantum.extract' op operand #1 must be 64-bit signless integer, but got 'i32'
    %5 = "quantum.extract"(%1, %4) : (!quantum.reg, i32) -> !quantum.bit
         ^
create_and_run_qnode:30:10: note: see current operation: %5 = "quantum.extract"(%1, %4) : (!quantum.reg, i32) -> !quantum.bit
Failed to parse module as MLIR source, retrying parsing as LLVM source
create_and_run_qnode: create_and_run_qnode:1:8: error: expected 'module asm'
module @create_and_run_qnode {
       ^
Failed to parse module as LLVM source


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/olivia/Code/shortalyst-dev/bug_ints.py", line 7, in <module>
    @qml.qjit
     ^^^^^^^^
  File "/home/olivia/.conda/envs/shortalyst/lib/python3.11/site-packages/pennylane/compiler/qjit_api.py", line 301, in qjit
    return qjit_loader(fn=fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/Code/catalyst/frontend/catalyst/jit.py", line 725, in qjit
    return QJIT(
           ^^^^^
  File "/home/olivia/Code/catalyst/frontend/catalyst/jit.py", line 101, in __init__
    self.aot_compile()
  File "/home/olivia/Code/catalyst/frontend/catalyst/jit.py", line 132, in aot_compile
    self.mlir_module, self.mlir = self.generate_ir()
                                  ^^^^^^^^^^^^^^^^^^
  File "/home/olivia/Code/catalyst/frontend/catalyst/jit.py", line 245, in generate_ir
    _, mlir_string, _ = canonicalizer.run(mlir_module, self.workspace)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/Code/catalyst/frontend/catalyst/compiler.py", line 505, in run
    return self.run_from_ir(
           ^^^^^^^^^^^^^^^^^
  File "/home/olivia/Code/catalyst/frontend/catalyst/compiler.py", line 470, in run_from_ir
    raise CompileError(*e.args) from e
catalyst.utils.exceptions.CompileError: Compilation failed:
create_and_run_qnode:30:10: error: 'quantum.extract' op operand #1 must be 64-bit signless integer, but got 'i32'
    %5 = "quantum.extract"(%1, %4) : (!quantum.reg, i32) -> !quantum.bit
         ^
create_and_run_qnode:30:10: note: see current operation: %5 = "quantum.extract"(%1, %4) : (!quantum.reg, i32) -> !quantum.bit
Failed to parse module as MLIR source, retrying parsing as LLVM source
create_and_run_qnode: create_and_run_qnode:1:8: error: expected 'module asm'
module @create_and_run_qnode {
       ^
Failed to parse module as LLVM source


```

**Comment by dime10** [comment]
Thanks for the report, this shouldn't be very difficult to fix :)
