### ISSUE TITLE
[BUG] Error when performing measurement on wire array with single wire

### ISSUE THREAD

**Issue by glassnotes** [PennyLaneAI/catalyst#614]
#### Issue description

* *Expected behavior:* Gates and mid-measurements can be applied in the same way to arrays of wires, even if the array has only one wire.

* *Actual behavior:* When a wire is an array with only a single element, performing mid-circuit measurements throws an error.

* *Reproduces how often:* Always, unless we directly index the 0'th element of the wire array.

* *System information:* (post the output of `import pennylane as qml; qml.about()`)

My install of Catalyst is from the branch ac3b90f9b69fefa0f24b15946ddfeacf6be36949.

```
Name: PennyLane
Version: 0.35.1
Summary: PennyLane is a cross-platform Python library for quantum computing, quantum machine learning, and quantum chemistry. Train a quantum computer the same way as a neural network.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /home/olivia/.conda/envs/shortalyst/lib/python3.11/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml, typing-extensions
Required-by: amazon-braket-pennylane-plugin, PennyLane-Catalyst, PennyLane_Lightning, PennyLane_Lightning_Kokkos

Platform info:           Linux-6.5.0-25-generic-x86_64-with-glibc2.35
Python version:          3.11.8
Numpy version:           1.26.4
Scipy version:           1.12.0
Installed devices:
- default.clifford (PennyLane-0.35.1)
- default.gaussian (PennyLane-0.35.1)
- default.mixed (PennyLane-0.35.1)
- default.qubit (PennyLane-0.35.1)
- default.qubit.autograd (PennyLane-0.35.1)
- default.qubit.jax (PennyLane-0.35.1)
- default.qubit.legacy (PennyLane-0.35.1)
- default.qubit.tf (PennyLane-0.35.1)
- default.qubit.torch (PennyLane-0.35.1)
- default.qutrit (PennyLane-0.35.1)
- null.qubit (PennyLane-0.35.1)
- lightning.kokkos (PennyLane_Lightning_Kokkos-0.35.1)
- nvidia.custatevec (PennyLane-Catalyst-0.6.0.dev0)
- nvidia.cutensornet (PennyLane-Catalyst-0.6.0.dev0)
- softwareq.qpp (PennyLane-Catalyst-0.6.0.dev0)
- braket.aws.ahs (amazon-braket-pennylane-plugin-1.24.6)
- braket.aws.qubit (amazon-braket-pennylane-plugin-1.24.6)
- braket.local.ahs (amazon-braket-pennylane-plugin-1.24.6)
- braket.local.qubit (amazon-braket-pennylane-plugin-1.24.6)
- lightning.qubit (PennyLane_Lightning-0.35.1)
```

#### Source code and tracebacks

Minimal example:

```python

import pennylane as qml
from catalyst import measure
import jax.numpy as jnp

@qml.qjit
def create_and_run_qnode():
    wires_part_1 = jnp.array([0], dtype=jnp.int64)
    wires_part_2 = jnp.arange(1, 4, dtype=jnp.int64)
    
    dev = qml.device("lightning.qubit", wires=jnp.concatenate((wires_part_1, wires_part_2)))

    @qml.qnode(dev)
    def circuit():
        # Both of these versions work
        qml.Hadamard(wires=wires_part_1)
        qml.Hadamard(wires=wires_part_1[0])

        # First one throws an error; the second one works
        m = measure(wires=wires_part_1)
        #m = measure(wires=wires_part_1[0])
        return qml.probs(wires=dev.wires)

    return circuit()

create_and_run_qnode()

```

The error message is

```
Traceback (most recent call last):
  File "/home/olivia/Code/shortalyst-dev/bug_measure.py", line 8, in <module>
    @qml.qjit
  File "/home/olivia/.conda/envs/shortalyst/lib/python3.11/site-packages/pennylane/compiler/qjit_api.py", line 301, in qjit
    return qjit_loader(fn=fn, *args, **kwargs)
  File "/home/olivia/Code/catalyst/frontend/catalyst/jit.py", line 725, in qjit
    return QJIT(
  File "/home/olivia/Code/catalyst/frontend/catalyst/jit.py", line 101, in __init__
    self.aot_compile()
  File "/home/olivia/Code/catalyst/frontend/catalyst/jit.py", line 129, in aot_compile
    self.jaxpr, self.out_treedef, self.c_sig = self.capture(self.user_sig or ())
  File "/home/olivia/Code/catalyst/frontend/catalyst/jit.py", line 220, in capture
    jaxpr, treedef = trace_to_jaxpr(
  File "/home/olivia/Code/catalyst/frontend/catalyst/jax_tracer.py", line 353, in trace_to_jaxpr
    jaxpr, out_treedef = make_jaxpr2(func, **make_jaxpr_kwargs)(*args, **kwargs)
  File "/home/olivia/Code/catalyst/frontend/catalyst/jax_extras/tracing.py", line 395, in make_jaxpr_f
    jaxpr, output_type, consts = trace_to_jaxpr_dynamic2(f)
  File "/home/olivia/Code/shortalyst-dev/bug_measure.py", line 26, in create_and_run_qnode
    return circuit()
  File "/home/olivia/Code/catalyst/frontend/catalyst/pennylane_extensions.py", line 170, in __call__
    res_flat = func_p.bind(flattened_fun, *args_flat, fn=self)
  File "/home/olivia/Code/catalyst/frontend/catalyst/pennylane_extensions.py", line 159, in _eval_quantum
    closed_jaxpr, out_type, out_tree = trace_quantum_function(
  File "/home/olivia/Code/catalyst/frontend/catalyst/jax_tracer.py", line 893, in trace_quantum_function
    qrp_out = trace_quantum_tape(tape, device, qreg_in, ctx, trace)
  File "/home/olivia/Code/catalyst/frontend/catalyst/jax_tracer.py", line 465, in trace_quantum_tape
    qrp2 = op.trace_quantum(ctx, device, trace, qrp)
  File "/home/olivia/Code/catalyst/frontend/catalyst/pennylane_extensions.py", line 1012, in trace_quantum
    qubit = qrp.extract([wire])[0]
  File "/home/olivia/Code/catalyst/frontend/catalyst/jax_tracer.py", line 214, in extract
    qubits.append(qextract_p.bind(qrp.base, w))
jax._src.source_info_util.JaxStackTraceBeforeTransformation: AssertionError: Scalar integer required for extract op!

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/olivia/Code/shortalyst-dev/bug_measure.py", line 8, in <module>
    @qml.qjit
     ^^^^^^^^
  File "/home/olivia/.conda/envs/shortalyst/lib/python3.11/site-packages/pennylane/compiler/qjit_api.py", line 301, in qjit
    return qjit_loader(fn=fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/Code/catalyst/frontend/catalyst/jit.py", line 725, in qjit
    return QJIT(
           ^^^^^
  File "/home/olivia/Code/catalyst/frontend/catalyst/jit.py", line 101, in __init__
    self.aot_compile()
  File "/home/olivia/Code/catalyst/frontend/catalyst/jit.py", line 132, in aot_compile
    self.mlir_module, self.mlir = self.generate_ir()
                                  ^^^^^^^^^^^^^^^^^^
  File "/home/olivia/Code/catalyst/frontend/catalyst/jit.py", line 233, in generate_ir
    mlir_module, ctx = lower_jaxpr_to_mlir(self.jaxpr, self.__name__)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/Code/catalyst/frontend/catalyst/jax_tracer.py", line 381, in lower_jaxpr_to_mlir
    mlir_module, ctx = jaxpr_to_mlir(func_name, jaxpr)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/Code/catalyst/frontend/catalyst/jax_extras/lowering.py", line 65, in jaxpr_to_mlir
    module, context = custom_lower_jaxpr_to_module(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/Code/catalyst/frontend/catalyst/jax_extras/lowering.py", line 133, in custom_lower_jaxpr_to_module
    lower_jaxpr_to_fun(
  File "/home/olivia/.conda/envs/shortalyst/lib/python3.11/site-packages/jax/_src/interpreters/mlir.py", line 1301, in lower_jaxpr_to_fun
    out_vals, tokens_out = jaxpr_subcomp(
                           ^^^^^^^^^^^^^^
  File "/home/olivia/.conda/envs/shortalyst/lib/python3.11/site-packages/jax/_src/interpreters/mlir.py", line 1494, in jaxpr_subcomp
    ans = lower_per_platform(rule_ctx, str(eqn.primitive),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.conda/envs/shortalyst/lib/python3.11/site-packages/jax/_src/interpreters/mlir.py", line 1602, in lower_per_platform
    return kept_rules[0](ctx, *rule_args, **rule_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/Code/catalyst/frontend/catalyst/jax_primitives.py", line 294, in _func_lowering
    symbol_name = _func_def_lowering(ctx.module_context, fn, call_jaxpr)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/Code/catalyst/frontend/catalyst/jax_primitives.py", line 252, in _func_def_lowering
    func_op = mlir.lower_jaxpr_to_fun(ctx, fn.__name__, call_jaxpr, tuple())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.conda/envs/shortalyst/lib/python3.11/site-packages/jax/_src/interpreters/mlir.py", line 1301, in lower_jaxpr_to_fun
    out_vals, tokens_out = jaxpr_subcomp(
                           ^^^^^^^^^^^^^^
  File "/home/olivia/.conda/envs/shortalyst/lib/python3.11/site-packages/jax/_src/interpreters/mlir.py", line 1494, in jaxpr_subcomp
    ans = lower_per_platform(rule_ctx, str(eqn.primitive),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/.conda/envs/shortalyst/lib/python3.11/site-packages/jax/_src/interpreters/mlir.py", line 1602, in lower_per_platform
    return kept_rules[0](ctx, *rule_args, **rule_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olivia/Code/catalyst/frontend/catalyst/jax_primitives.py", line 639, in _qextract_lowering
    assert ir.IntegerType.isinstance(qubit_idx.type), "Scalar integer required for extract op!"
AssertionError: Scalar integer required for extract op!
```

#### Additional information

My use case here involves sending registers into the function that gets qjitted, which is why they are defined as JAX arrays. There may be a better way to manage this, or the register concatenation, but I think it's a bit unexpected in any case.

**Comment by erick-xanadu** [comment]
Hi @glassnotes, this is a current limitation, but I don't think it would be too difficult to generalize the measurement operation to allow measurement on multiple wires in a single instruction. Thanks!
