### ISSUE TITLE
[BUG] catalyst.for_loop default argument `i` cannot be used as a concrete value

### ISSUE THREAD

**Issue by paul0403** [PennyLaneAI/catalyst#759]
The following works:

```python
def do_nothing(wires):
	qml.Identity(wires=wires[0])
	qml.Identity(wires=wires[1])

dev = qml.device("lightning.qubit", wires=4)

@qjit
@qml.qnode(dev)
def circuit():
	for i in range(0,2,1):
		do_nothing(jnp.arange(2*i, 2*i+1))
	return qml.expval(qml.PauliZ(wires=[0]))

print(circuit())

>>> 1.0
```

But swapping out this native python for loop with catalyst for loop breaks:
```python
def do_nothing(wires):
	qml.Identity(wires=wires[0])
	qml.Identity(wires=wires[1])

dev = qml.device("lightning.qubit", wires=4)

@qjit
@qml.qnode(dev)
def circuit():
	@catalyst.for_loop(0,2,1)
	def loop_body(i):
		do_nothing(jnp.arange(2*i, 2*i+1))
	loop_body()
	return qml.expval(qml.PauliZ(wires=[0]))

print(circuit())

>>>
Traceback (most recent call last):
  File "/home/paul.wang/small_playgrounds_dump/symmetry_demo/observable_test.py", line 23, in <module>
    def circuit():
  File "/home/paul.wang/catalyst/frontend/catalyst/jit.py", line 822, in qjit
    return QJIT(fn, CompileOptions(**kwargs))
  File "/home/paul.wang/catalyst/frontend/catalyst/jit.py", line 114, in __init__
    self.aot_compile()
  File "/home/paul.wang/catalyst/frontend/catalyst/jit.py", line 146, in aot_compile
    self.jaxpr, self.out_treedef, self.c_sig = self.capture(self.user_sig or ())
  File "/home/paul.wang/catalyst/frontend/catalyst/debug/instruments.py", line 143, in wrapper
    return fn(*args, **kwargs)
  File "/home/paul.wang/catalyst/frontend/catalyst/jit.py", line 244, in capture
    jaxpr, treedef = trace_to_jaxpr(
  File "/home/paul.wang/catalyst/frontend/catalyst/jax_tracer.py", line 353, in trace_to_jaxpr
    jaxpr, out_treedef = make_jaxpr2(func, **make_jaxpr_kwargs)(*args, **kwargs)
  File "/home/paul.wang/catalyst/frontend/catalyst/jax_extras/tracing.py", line 402, in make_jaxpr_f
    jaxpr, output_type, consts = trace_to_jaxpr_dynamic2(f)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/profiler.py", line 336, in wrapper
    return func(*args, **kwargs)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/interpreters/partial_eval.py", line 2324, in trace_to_jaxpr_dynamic2
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(fun, main, debug_info)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/interpreters/partial_eval.py", line 2339, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/linear_util.py", line 191, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/paul.wang/catalyst/frontend/catalyst/qfunc.py", line 86, in __call__
    res_flat = func_p.bind(flattened_fun, *args_flat, fn=self)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/core.py", line 2309, in bind
    outs = top_trace.process_call(self, fun_, tracers, params)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/interpreters/partial_eval.py", line 2012, in process_call
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(f, self.main, debug_info=dbg)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/interpreters/partial_eval.py", line 2339, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/linear_util.py", line 191, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/paul.wang/catalyst/frontend/catalyst/qfunc.py", line 75, in _eval_quantum
    closed_jaxpr, out_type, out_tree = trace_quantum_function(
  File "/home/paul.wang/catalyst/frontend/catalyst/jax_tracer.py", line 837, in trace_quantum_function
    return_values_flat = wffa.call_wrapped(*in_classical_tracers)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/linear_util.py", line 191, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/paul.wang/small_playgrounds_dump/symmetry_demo/observable_test.py", line 31, in circuit
    loop_body()
  File "/home/paul.wang/catalyst/frontend/catalyst/api_extensions/control_flow.py", line 678, in __call__
    return self._call_with_quantum_ctx(ctx, *init_state)
  File "/home/paul.wang/catalyst/frontend/catalyst/api_extensions/control_flow.py", line 630, in _call_with_quantum_ctx
    inner_trace.full_raise(t) for t in wffa.call_wrapped(*arg_classical_tracers)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/linear_util.py", line 191, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/paul.wang/small_playgrounds_dump/symmetry_demo/observable_test.py", line 30, in loop_body
    do_nothing(jnp.arange(2*i, 2*i+1))
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 2456, in arange
    stop = core.concrete_or_error(None, stop, "It arose in the jnp.arange argument 'stop'")
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/core.py", line 1527, in concrete_or_error
    raise ConcretizationTypeError(val, context)
jax.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: traced array with shape int64[].
It arose in the jnp.arange argument 'stop'

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
```
Since we are attempting to use the abstract value `i` as concrete values specifying which subset of wires to work on. 

This is a common usage pattern when, say, preparing states in batches. In this example the same 2-bit module is attached to qubits (0,1) then qubits (2,3); similar patterns include preparing two-qubit singlet states across a big circuit with many such pairs, requiring a loop over the pairs. 

This bug was originally discovered when trying to port the PL demo https://pennylane.ai/qml/demos/tutorial_eqnn_force_field/#le23 into catalyst, credit @josh146 : 
https://colab.research.google.com/drive/1E70V8C4gVaoMyQD9xdEu1OxM5Jd4sy61?usp=sharing

**Comment by paul0403** [comment]
At the very least, a warning needs to be raised telling the user that native python loop should be used when the iterator's concrete value is important.

**Comment by josh146** [comment]
Nice detective work @paul0403 🕵️

**Comment by josh146** [comment]
@dime10 my understanding is that the above pattern is not allowed in JAX because it doesn't support dynamic shaped arrays (and `jnp.arange` with an abstract stopping value would create one), but should this work in catalyst with the recent dynamic shape array support?

**Comment by paul0403** [comment]
I can confirm it's an issue with `jnp.arange`, as the following works:

```python
def do_nothing(wires):
	qml.Identity(wires=wires[0])
	qml.Identity(wires=wires[1])

dev = qml.device("lightning.qubit", wires=4)

@qjit
@qml.qnode(dev)
def circuit():
	@catalyst.for_loop(0,2,1)
	def loop_body(i):
		#do_nothing(jnp.arange(2*i, 2*i+1))
		do_nothing([2*i, 2*i+1])
	loop_body()
	return qml.expval(qml.PauliZ(wires=[0]))

print(circuit())

>>>
1.0
```

**Comment by paul0403** [comment]
This is also fine:

```python
def do_nothing(wires):
	qml.Identity(wires=wires[0])
	qml.Identity(wires=wires[1])

dev = qml.device("lightning.qubit", wires=4)

@qjit
@qml.qnode(dev)
def circuit():
	@catalyst.for_loop(0,2,1)
	def loop_body(i):
		#do_nothing(jnp.arange(2*i, 2*i+1, dtype=int))
		#do_nothing([2*i, 2*i+1])
		do_nothing(jnp.ones(2, dtype=int))
	loop_body()
	return qml.expval(qml.PauliZ(wires=[0]))

print(circuit())

>>>
1.0
```

But one has to explicitly specify `dtype=int`; doing so in `jnp.arange` does not work.

**Comment by dime10** [comment]
> In which case, maybe the bug here is more 'add dynamic shape support to jnp.arange' (similar to what we did with jnp.ones and jnp.zeros)

Agreed, this is not a for loop issue, but that `arange` doesn't accept dynamic values. I don't remember if we did anything specific to get `jnp.ones` and `jnp.zeros` working 🤔 I also can't remember if dynamic shapes need to be specifically enabled or not. So we should investigate wether there is any dynamic support for `arange` in JAX, and if not this would be more of a feature improvement to patch in that support.

**Comment by josh146** [comment]
here is the logic for the `jnp.array` argument checking:

https://github.com/google/jax/blob/1e01fa7b0f1355c522f8420569dc778f2633c629/jax/_src/numpy/lax_numpy.py#L3143-L3154

It's not clear to me why the concrete checks for stop and step appear _outside_ the branch for dynamic shape checking.

**Comment by dime10** [comment]
> here is the logic for the `jnp.array` argument checking:
> 
> https://github.com/google/jax/blob/1e01fa7b0f1355c522f8420569dc778f2633c629/jax/_src/numpy/lax_numpy.py#L3143-L3154
> 
> It's not clear to me why the concrete checks for stop and step appear _outside_ the branch for dynamic shape checking.

Maybe a bug?

**Comment by paul0403** [comment]
Since the length of the `arange` is fixed in this use case, and only the starting number is dynamic, the following is a neat workaround:

```python
def do_nothing(wires):
	qml.Identity(wires=wires[0])
	qml.Identity(wires=wires[1])

dev = qml.device("lightning.qubit", wires=4)

@qjit
@qml.qnode(dev)
def circuit():
	@catalyst.for_loop(0,2,1)
	def loop_body(i):
		do_nothing(jnp.arange(2)+2*i)
	loop_body()
	return qml.expval(qml.PauliZ(wires=[0]))

print(circuit())

>>>
1.0
```

Although full support for `jnp.arrange` would be nice, or even just a warning hinting the user to do this.
