### ISSUE TITLE
[BUG] `qml.pauli_decompose` fails inside qjit, even with jnp arrays as inputs and `check_hermitian` turned off

### ISSUE THREAD

**Issue by paul0403** [PennyLaneAI/catalyst#797]
expected:
```python
dev = qml.device("lightning.qubit", wires=1)

#@qjit
def f(mat):
	coeffs, unitaries = qml.pauli_decompose(mat, check_hermitian=False).terms()
	return coeffs, unitaries

x = jnp.array([[1,2],[3,4] ])
print(f(x))

>>>
(Array([ 2.5+0.j ,  2.5+0.j , -0. -0.5j, -1.5+0.j ], dtype=complex128), [I(0), X(0), Y(0), Z(0)])
```

but got:
```python
dev = qml.device("lightning.qubit", wires=1)

@qjit
def f(mat):
	coeffs, unitaries = qml.pauli_decompose(mat, check_hermitian=False).terms()
	return coeffs, unitaries

x = jnp.array([[1,2],[3,4] ])
print(f(x))

>>>
Traceback (most recent call last):
  File "/home/paul.wang/small_playgrounds_dump/qsvt_demo/pauli_decompose.py", line 19, in <module>
    print(f(x))
  File "/home/paul.wang/.local/lib/python3.10/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
  File "/home/paul.wang/catalyst/frontend/catalyst/jit.py", line 513, in __call__
    requires_promotion = self.jit_compile(args)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
  File "/home/paul.wang/catalyst/frontend/catalyst/jit.py", line 582, in jit_compile
    self.jaxpr, self.out_treedef, self.c_sig = self.capture(args)
  File "/home/paul.wang/catalyst/frontend/catalyst/debug/instruments.py", line 143, in wrapper
    return fn(*args, **kwargs)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
  File "/home/paul.wang/catalyst/frontend/catalyst/jit.py", line 640, in capture
    jaxpr, treedef = trace_to_jaxpr(
  File "/home/paul.wang/.local/lib/python3.10/site-packages/pennylane/logging/decorators.py", line 61, in wrapper_entry
    return func(*args, **kwargs)
  File "/home/paul.wang/catalyst/frontend/catalyst/jax_tracer.py", line 370, in trace_to_jaxpr
    jaxpr, out_treedef = make_jaxpr2(func, **make_jaxpr_kwargs)(*args, **kwargs)
  File "/home/paul.wang/catalyst/frontend/catalyst/jax_extras/tracing.py", line 410, in make_jaxpr_f
    jaxpr, output_type, consts = trace_to_jaxpr_dynamic2(f)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/profiler.py", line 336, in wrapper
    return func(*args, **kwargs)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/interpreters/partial_eval.py", line 2324, in trace_to_jaxpr_dynamic2
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(fun, main, debug_info)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/interpreters/partial_eval.py", line 2339, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/linear_util.py", line 191, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/paul.wang/small_playgrounds_dump/qsvt_demo/pauli_decompose.py", line 15, in f
    coeffs, unitaries = qml.pauli_decompose(mat, check_hermitian=False).terms()
  File "/home/paul.wang/.local/lib/python3.10/site-packages/pennylane/pauli/conversion.py", line 323, in pauli_decompose
    coeffs, obs = _generalized_pauli_decompose(
  File "/home/paul.wang/.local/lib/python3.10/site-packages/pennylane/pauli/conversion.py", line 209, in _generalized_pauli_decompose
    if not qml.math.allclose(coefficient, 0):
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/core.py", line 768, in __bool__
    return self.aval._bool(self)
  File "/home/paul.wang/.local/lib/python3.10/site-packages/jax/_src/core.py", line 1510, in error
    raise TracerBoolConversionError(arg)
jax.errors.TracerBoolConversionError: Attempted boolean conversion of traced array with shape bool[]..
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerBoolConversionError
```

**Comment by erick-xanadu** [comment]
This is most likely an issue with Pennylane itself rather than Catalyst. We can chat about it tomorrow. Thanks for reporting it :)

**Comment by dime10** [comment]
Yes this needs to be opened in PennyLane :)

**Comment by paul0403** [comment]
opened in core PL: 
https://github.com/PennyLaneAI/pennylane/issues/5817
